# Course Introduction — Solutions

**Warning:** Try to complete the exercises in `demos/02_course_introduction.ipynb` on your own before looking at these solutions!

---

## Setup

In [1]:
import numpy as np
import pandas as pd

print("\u2713 Libraries imported!")

✓ Libraries imported!

---
## NumPy Solutions

### Task 1: Create a Linear Dataset

### Solution

In [2]:
feature = np.arange(6, 21)   # 6 to 20 inclusive (21 is exclusive)
label = 3 * feature + 4      # Apply linear formula to each element

print("Feature:", feature)
print("Label:", label)

Feature: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label: [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]

**Explanation:**
- `np.arange(6, 21)` creates integers from 6 to 20 — the stop value 21 is exclusive
- NumPy **broadcasting** applies `3 * feature + 4` element-wise to the entire array in one operation

### Task 2: Add Noise to the Dataset

### Solution

In [3]:
noise = np.random.random(len(label)) * 4 - 2  # Random values in [-2, +2]
noisy_label = label + noise

print("Original label:", label)
print("Noise:", noise)
print("Noisy label:", noisy_label)

Original label: [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
Noise: [-0.58460142 -1.70392564 -1.10354768 -0.77409771 -0.94271654  0.92585084
 -1.53611076  0.03200728 -1.92767803  1.2092032  -1.48199435  0.67573326
  1.0834763  -0.3409547  -0.59048304]
Noisy label: [21.41539858 23.29607436 26.89645232 30.22590229 33.05728346 37.92585084
 38.46388924 43.03200728 44.07232197 50.2092032  50.51800565 55.67573326
 59.0834763  60.6590453  63.40951696]

**Explanation:**
- `np.random.random()` generates values in [0, 1)
- Multiply by 4 to get range [0, 4), then subtract 2 to shift to [-2, +2)
- General formula: `random * (max - min) + min`
- Alternative: `np.random.uniform(-2, 2, len(label))`

### Task 3: Array Statistics

### Solution

In [4]:
mean_value = np.mean(noisy_label)
max_value = np.max(noisy_label)
min_value = np.min(noisy_label)
std_value = np.std(noisy_label)

print(f"Mean: {mean_value}")
print(f"Max: {max_value}")
print(f"Min: {min_value}")
print(f"Std: {std_value}")

Mean: 42.52934406769949
Max: 63.409516962238506
Min: 21.415398577565565
Std: 13.356362473974114

**Explanation:**
- NumPy provides these as both functions (`np.mean(arr)`) and methods (`arr.mean()`)
- Standard deviation measures how spread out the values are from the mean
- These statistics are fundamental in ML for understanding your data

### Task 4: Create a 2D Array

### Solution

In [5]:
zeros_matrix = np.zeros((4, 5))                     # 4x5 matrix of zeros
ones_matrix = np.ones((4, 5))                       # 4x5 matrix of ones
random_matrix = np.random.randint(10, 51, (4, 5))   # 4x5 matrix of random ints [10, 50]

print("Zeros shape:", zeros_matrix.shape)
print("Ones shape:", ones_matrix.shape)
print("Random matrix:\n", random_matrix)

Zeros shape: (4, 5)
Ones shape: (4, 5)
Random matrix:
 [[35 19 20 40 22]
 [48 35 19 39 31]
 [31 26 31 32 19]
 [17 17 37 26 10]]

**Explanation:**
- Shape is specified as a tuple: `(rows, columns)` — here `(4, 5)` means 4 rows, 5 columns
- `np.random.randint(10, 51, (4, 5))` uses 51 because the upper bound is exclusive — so we get integers from 10 to 50

### Task 5: Array Reshaping

### Solution

In [6]:
sequence = np.arange(1, 13)        # [1, 2, 3, ..., 12]
reshaped = sequence.reshape(3, 4)  # Reshape to 3 rows x 4 columns

print("Original:", sequence)
print("\nReshaped (3x4):\n", reshaped)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

**Explanation:**
- `np.arange(1, 13)` creates 12 elements
- `.reshape(3, 4)` rearranges into 3 rows and 4 columns — total elements must match (12 = 3 x 4)
- Elements fill row by row (row-major order)

---
## Pandas Solutions

First, load the Titanic dataset:

In [7]:
titanic = pd.read_csv('../datasets/titanic.csv')
print(f"Loaded {len(titanic)} rows")
titanic.head()

Loaded 887 rows

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

### Task 6: Filter by Gender

### Solution

In [8]:
female_passengers = titanic[titanic['Sex'] == 'female']
male_passengers = titanic[titanic['Sex'] == 'male']

print(f"Female passengers: {len(female_passengers)}")
print(f"Male passengers: {len(male_passengers)}")

Female passengers: 314
Male passengers: 573

**Explanation:**
- `titanic['Sex'] == 'female'` creates a boolean Series (True/False for each row)
- Using this as an index keeps only the rows where the condition is True
- This is called **boolean indexing** and is one of the most important Pandas operations

### Task 7: Calculate Survival Rate by Gender

### Solution

In [9]:
female_survival_rate = (female_passengers['Survived'].sum() / len(female_passengers)) * 100
male_survival_rate = (male_passengers['Survived'].sum() / len(male_passengers)) * 100

print(f"Female survival rate: {female_survival_rate:.1f}%")
print(f"Male survival rate: {male_survival_rate:.1f}%")

Female survival rate: 74.2%
Male survival rate: 19.0%

**Explanation:**
- The 'Survived' column contains 1 (survived) and 0 (died), so `.sum()` counts survivors
- Dividing by total passengers gives the proportion, multiplied by 100 for a percentage
- Shorter alternative: `female_passengers['Survived'].mean() * 100` — `.mean()` on 0/1 values gives the proportion directly

### Task 8: Create a New Column

### Solution

In [10]:
titanic['Family_Size'] = titanic['Siblings/Spouses Aboard'] + titanic['Parents/Children Aboard'] + 1

titanic[['Name', 'Family_Size', 'Survived']].head(10)

                                                Name  Family_Size  Survived
0                             Mr. Owen Harris Braund            2         0
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...            2         1
2                              Miss. Laina Heikkinen            1         1
3        Mrs. Jacques Heath (Lily May Peel) Futrelle            2         1
4                            Mr. William Henry Allen            1         0
5                                    Mr. James Moran            1         0
6                             Mr. Timothy J McCarthy            1         0
7                      Master. Gosta Leonard Palsson            5         0
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson            3         1
9                 Mrs. Nicholas (Adele Achem) Nasser            2         1

**Explanation:**
- Assigning to `titanic['Family_Size']` creates a new column
- Pandas adds the two columns element-wise, then adds 1 for the passenger themselves
- The new column is immediately available for further analysis

### Task 9: Find the Most Expensive Ticket

### Solution

In [11]:
max_fare = titanic['Fare'].max()
most_expensive = titanic[titanic['Fare'] == max_fare]

print(f"Maximum fare: ${max_fare:.2f}")
print("\nPassenger(s) with most expensive ticket:")
most_expensive[['Name', 'Pclass', 'Fare']]

Maximum fare: $512.33

Passenger(s) with most expensive ticket:

                                  Name  Pclass      Fare
257                    Miss. Anna Ward       1  512.3292
676  Mr. Thomas Drake Martinez Cardeza       1  512.3292
733              Mr. Gustave J Lesurer       1  512.3292

**Explanation:**
- `.max()` returns the single largest value in the column
- We then filter for all rows matching this value — there could be multiple passengers with the same fare
- Alternative: `titanic.nlargest(1, 'Fare')` returns the row(s) with the highest fare directly

### Task 10: Group by Class and Calculate Average Age

### Solution

In [12]:
average_age_by_class = titanic.groupby('Pclass')['Age'].mean()

print("Average age by passenger class:")
print(average_age_by_class)

Average age by passenger class:
Pclass
1    38.788981
2    29.868641
3    25.188747
Name: Age, dtype: float64

**Explanation:**
- `.groupby('Pclass')` splits the data into groups (one per class)
- `['Age']` selects the Age column within each group
- `.mean()` calculates the average for each group
- Notice that 1st class passengers tend to be older — wealthier passengers could afford better tickets

### Task 11: Multiple Conditions Filter

### Solution

In [13]:
filtered_passengers = titanic[
    (titanic['Sex'] == 'female') &
    (titanic['Pclass'] == 1) &
    (titanic['Age'] < 30)
]

print(f"Number of young first-class female passengers: {len(filtered_passengers)}")
print("\nFirst few:")
filtered_passengers[['Name', 'Age', 'Pclass', 'Sex']].head()

Number of young first-class female passengers: 31

First few:

                                       Name   Age  Pclass     Sex
87                Miss. Mabel Helen Fortune  23.0       1  female
135             Miss. Helen Monypeny Newsom  19.0       1  female
150        Mrs. Thomas (Edith Wearne) Pears  22.0       1  female
288                      Miss. Ellen Barber  26.0       1  female
289  Mrs. Dickinson H (Helen Walton) Bishop  19.0       1  female

**Explanation:**
- Combine multiple conditions with `&` (AND) — each condition must be in parentheses
- Other operators: `|` for OR, `~` for NOT
- A row is included only when **all** conditions are True

### Task 12: Missing Data Analysis

### Solution

In [14]:
missing_counts = titanic.isnull().sum()
age_missing_percent = (titanic['Age'].isnull().sum() / len(titanic)) * 100

print("Missing values per column:")
print(missing_counts)
print(f"\nPercentage of missing Age values: {age_missing_percent:.1f}%")

Missing values per column:
Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
Family_Size                0
dtype: int64

Percentage of missing Age values: 0.0%

**Explanation:**
- `.isnull()` creates a boolean DataFrame where True = missing value
- `.sum()` counts True values per column
- Missing data is very common in real datasets — handling it properly is a key part of data preprocessing (covered in later notebooks)

---
## Summary

In these solutions you practiced:

**NumPy:**

- Creating arrays with `np.arange()`, `np.zeros()`, `np.ones()`
- Generating random data with `np.random.random()` and `np.random.randint()`
- Computing statistics with `np.mean()`, `np.max()`, `np.min()`, `np.std()`
- Reshaping arrays with `.reshape()`

**Pandas:**

- Boolean filtering with single and multiple conditions
- Creating new columns from existing ones
- Aggregating data with `.groupby()` and `.mean()`
- Detecting missing data with `.isnull()`

---